/*!
 * reveal.js Zoom plugin
 */
const e={id:"zoom",init:e=>{e.getRevealElement().addEventListener("mousedown",(t=>{const n=/Linux/.test(window.navigator.platform)?"ctrl":"alt",i=`${e.getConfig().zoomKey?e.getConfig().zoomKey:n}Key`,d=e.getConfig().zoomLevel?e.getConfig().zoomLevel:2;t[i]&&!e.isOverview()&&(t.preventDefault(),o.to({x:t.clientX,y:t.clientY,scale:d,pan:!1}))}))},destroy:()=>{o.reset()}};var t=()=>e;
/*!
 * zoom.js 0.3 (modified for use with reveal.js)
 * http://lab.hakim.se/zoom-js
 * MIT licensed
 *
 * Copyright (C) 2011-2014 Hakim El Hattab, http://hakim.se
 */const o=(()=>{let e=1,t=0,n=0,i=-1,d=-1;const s="transform"in document.body.style;function l(t,o){const n=y();if(t.width=t.width||1,t.height=t.height||1,t.x-=(window.innerWidth-t.width*o)/2,t.y-=(window.innerHeight-t.height*o)/2,s)if(1===o)document.body.style.transform="";else{const e=`${n.x}px ${n.y}px`,i=`translate(${-t.x}px,${-t.y}px) scale(${o})`;document.body.style.transformOrigin=e,document.body.style.transform=i}else 1===o?(document.body.style.position="",document.body.style.left="",document.body.style.top="",document.body.style.width="",document.body.style.height="",document.body.style.zoom=""):(document.body.style.position="relative",document.body.style.left=-(n.x+t.x)/o+"px",document.body.style.top=-(n.y+t.y)/o+"px",document.body.style.width=100*o+"%",document.body.style.height=100*o+"%",document.body.style.zoom=o);e=o,document.documentElement.classList&&(1!==e?document.documentElement.classList.add("zoomed"):document.documentElement.classList.remove("zoomed"))}function c(){const o=.12*window.innerWidth,i=.12*window.innerHeight,d=y();n<i?window.scroll(d.x,d.y-14/e*(1-n/i)):n>window.innerHeight-i&&window.scroll(d.x,d.y+(1-(window.innerHeight-n)/i)*(14/e)),t<o?window.scroll(d.x-14/e*(1-t/o),d.y):t>window.innerWidth-o&&window.scroll(d.x+(1-(window.innerWidth-t)/o)*(14/e),d.y)}function y(){return{x:void 0!==window.scrollX?window.scrollX:window.pageXOffset,y:void 0!==window.scrollY?window.scrollY:window.pageYOffset}}return s&&(document.body.style.transition="transform 0.8s ease"),document.addEventListener("keyup",(t=>{1!==e&&27===t.keyCode&&o.out()})),document.addEventListener("mousemove",(o=>{1!==e&&(t=o.clientX,n=o.clientY)})),{to:t=>{if(1!==e)o.out();else{if(t.x=t.x||0,t.y=t.y||0,t.element){const e=20,o=t.element.getBoundingClientRect();t.x=o.left-e,t.y=o.top-e,t.width=o.width+2*e,t.height=o.height+2*e}void 0!==t.width&&void 0!==t.height&&(t.scale=Math.max(Math.min(window.innerWidth/t.width,window.innerHeight/t.height),1)),t.scale>1&&(t.x*=t.scale,t.y*=t.scale,l(t,t.scale),!1!==t.pan&&(i=setTimeout((()=>{d=setInterval(c,1e3/60)}),800)))}},out:()=>{clearTimeout(i),clearInterval(d),l({x:0,y:0},1),e=1},magnify:function(e){this.to(e)},reset:function(){this.out()},zoomLevel:()=>e}})();export{t as default};
